//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace Company.FinalVersionSoSa
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class ImmediateLevel
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateImmediateLevelMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Solution_Name == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.FinalVersionSoSa.FinalVersionSoSaDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"ImmediateLevel", this.Name, "Solution_Name"),
						"DSL0001", this);
			}
		} // ValidateImmediateLevelMultiplicity
	} // class ImmediateLevel
} // Company.FinalVersionSoSa

	
 