//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.FinalVersionSoSa
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "FinalVersionSoSa";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"FinalVersionSoSa";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FinalVersionSoSaDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FinalVersionSoSaCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FinalVersionSoSaExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FinalVersionSoSaCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFinalVersionSoSaExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FinalVersionSoSaCommandSetId), 0x0001);
	
		// Package identifier
		public const string FinalVersionSoSaPackageId = "c2cc025d-da05-4ce4-8fb6-20366a336fca";
		
		// Editor factory identifier
		public const string FinalVersionSoSaEditorFactoryId = "e465a524-0453-4904-b89c-efd5e895ae79";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FinalVersionSoSaModelExplorerToolWindowId = "b0b98e31-2738-4a17-953a-3c3e1532b605";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.FinalVersionSoSa
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FinalVersionSoSaCommandSetId = "78780317-b8ec-48a7-b89f-0f7064080624";
	}
}